// State fields transcribed from unitree_sdk2_python commit
// 65691c8a8bc53b98d3976dba4dbf9d5d20b2e7f5. See LICENSE.unitree.
module unitree_hg { module msg { module dds_ {
@final struct IMUState_ {
  float quaternion[4]; float gyroscope[3]; float accelerometer[3];
  float rpy[3]; short temperature;
};
@final struct MotorState_ {
  octet mode; float q; float dq; float ddq; float tau_est;
  short temperature[2]; float vol; unsigned long sensor[2];
  unsigned long motorstate; unsigned long reserve[4];
};
@final struct LowState_ {
  unsigned long version[2]; octet mode_pr; octet mode_machine;
  unsigned long tick; IMUState_ imu_state; MotorState_ motor_state[35];
  octet wireless_remote[40]; unsigned long reserve[4]; unsigned long crc;
};
}; }; };
